export const connectorIcons: Record<string, string> = {
  Gmail: "/gmail.png",
  Slack: "/slack.png",
  GitHub: "/github.png",
  Reddit: "/reddit.png",
  Calendar: "/calendar.png",
  LinkedIn: "/linkedin.png",
  "Google Meet": "/meet.png",
  Todoist: "/todoist.jpg",
  Attio: "/attio.jpeg",
  "Hacker News": "/hacker-news.jpeg",
  HubSpot: "/hubspot.png",
  Jira: "/jira.jpeg",
  Linear: "/linear.jpeg",
  Notion: "/notion.webp",
  Outlook: "/outlook.jpeg",
  Typeform: "/typeform.png",
  Ashby: "/ashby.webp",
  YouTube: "/youtub.png",
  "Google Docs": "/docs.png",
  "Google Sheets": "/sheets.png",
};

export const models = [
  {
    value: "claude-sonnet-3.5",
    label: "Claude Sonnet 3.5",
    short: "Sonnet 3.5",
    logo: "/claude.png",
    disabled: false,
  },
  {
    value: "claude-opus-4.5",
    label: "Claude Opus 4.5",
    short: "Opus 4.5",
    logo: "/claude.png",
    disabled: true,
  },
  {
    value: "gpt-4.1-mini",
    label: "GPT-4.1 mini",
    short: "4.1 mini",
    logo: "/chatgpt.png",
    disabled: false,
  },
  {
    value: "gpt-4.1",
    label: "GPT-4.1",
    short: "4.1",
    logo: "/chatgpt.png",
    disabled: true,
  },
  {
    value: "gpt-5.1",
    label: "GPT-5.1",
    short: "5.1",
    logo: "/chatgpt.png",
    disabled: true,
  },
];
