export const connectorIcons: Record<string, string> = {
  Gmail: "/gmail.png",
  Slack: "/slack.png",
  GitHub: "/github.png",
  Reddit: "/reddit.png",
  Calendar: "/calendar.png",
  LinkedIn: "/linkedin.png",
  "Google Meet": "/meet.png",
  Todoist: "/todoist.jpg",
  Attio: "/attio.jpeg",
  "Hacker News": "/hacker-news.jpeg",
  HubSpot: "/hubspot.png",
  Jira: "/jira.jpeg",
  Linear: "/linear.jpeg",
  Notion: "/notion.webp",
  Outlook: "/outlook.jpeg",
  Typeform: "/typeform.png",
  Ashby: "/ashby.webp",
  YouTube: "/youtub.png",
  "Google Docs": "/docs.png",
  "Google Sheets": "/sheets.png",
};
